# Generated by Django 4.2.1 on 2023-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.IntegerField(default=True),
        ),
    ]
