# Generated by Django 4.2.1 on 2023-11-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_record_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='zip_code',
        ),
    ]
